changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: "\U0001F680 Features"
      labels:
        - enhancement
        - feature
    - title: "\U0001F41B Bug Fixes"
      labels:
        - bug
        - fix
    - title: "\U0001F4DA Documentation"
      labels:
        - documentation
    - title: "\U0001F9F0 Maintenance"
      labels:
        - chore
        - maintenance
        - dependencies
    - title: "\U0001F4E6 Other Changes"
      labels:
        - "*"
